package aws

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"go.uber.org/zap"
)

// Validator validates AWS federated identity tokens by making actual AWS STS calls
type Validator struct {
	logger    *zap.Logger
	audiences []string
}

// AWSTokenData represents the structure of AWS token data as generated by clients
type AWSTokenData struct {
	URL     string    `json:"url"`
	Method  string    `json:"method"`
	Headers []Header  `json:"headers"`
}

// Header represents an HTTP header key-value pair
type Header struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// AWSValidationResult contains the result of AWS token validation
type AWSValidationResult struct {
	ARN       string
	AccountID string
	UserID    string
	Region    string
}

// NewValidator creates a new AWS token validator
func NewValidator(logger *zap.Logger, audiences []string) (*Validator, error) {
	return &Validator{
		logger:    logger,
		audiences: audiences,
	}, nil
}

// Validate validates an AWS federated identity token by parsing it and making an STS call
func (v *Validator) Validate(ctx context.Context, tokenData string) (map[string]string, error) {
	v.logger.Debug("validating AWS token")

	// URL decode the token
	decodedToken, err := url.QueryUnescape(tokenData)
	if err != nil {
		return nil, fmt.Errorf("failed to URL decode token: %w", err)
	}

	// Parse the JSON token
	var awsTokenData AWSTokenData
	if err := json.Unmarshal([]byte(decodedToken), &awsTokenData); err != nil {
		return nil, fmt.Errorf("failed to parse AWS token JSON: %w", err)
	}

	// Validate the audience if configured
	if len(v.audiences) > 0 {
		if err := v.validateAudience(&awsTokenData); err != nil {
			return nil, fmt.Errorf("audience validation failed: %w", err)
		}
	}

	// Extract region from the token URL
	region, err := v.extractRegionFromToken(&awsTokenData)
	if err != nil {
		return nil, fmt.Errorf("failed to extract region from token: %w", err)
	}

	// Validate the token by making the actual AWS STS call
	result, err := v.validateWithAWS(ctx, &awsTokenData, region)
	if err != nil {
		return nil, fmt.Errorf("AWS STS validation failed: %w", err)
	}

	// Convert result to metadata map
	metadata := map[string]string{
		"io.flipt.auth.aws.arn":    result.ARN,
		"io.flipt.auth.aws.region": result.Region,
	}

	if result.AccountID != "" {
		metadata["io.flipt.auth.aws.account_id"] = result.AccountID
	}

	if result.UserID != "" {
		metadata["io.flipt.auth.aws.user_id"] = result.UserID
	}

	v.logger.Debug("AWS token validation successful", 
		zap.String("arn", result.ARN),
		zap.String("account_id", result.AccountID),
		zap.String("region", result.Region))

	return metadata, nil
}

// validateAudience checks if the token contains the expected audience
func (v *Validator) validateAudience(tokenData *AWSTokenData) error {
	var tokenAudience string
	for _, header := range tokenData.Headers {
		if header.Key == "x-goog-cloud-target-resource" {
			tokenAudience = header.Value
			break
		}
	}

	if tokenAudience == "" {
		return fmt.Errorf("token does not contain required x-goog-cloud-target-resource header")
	}

	// Check if the token audience matches any of the configured audiences
	for _, audience := range v.audiences {
		if tokenAudience == audience {
			return nil
		}
	}
	
	return fmt.Errorf("token audience mismatch: token contains %q, but expected one of %v", 
		tokenAudience, v.audiences)
}

// extractRegionFromToken extracts the AWS region from the STS URL in the token
func (v *Validator) extractRegionFromToken(tokenData *AWSTokenData) (string, error) {
	parsedURL, err := url.Parse(tokenData.URL)
	if err != nil {
		return "", fmt.Errorf("invalid STS URL in token: %w", err)
	}

	// AWS STS URLs follow the pattern: https://sts.<region>.amazonaws.com/
	// or https://sts.amazonaws.com/ for us-east-1 (default)
	host := parsedURL.Host
	if host == "sts.amazonaws.com" {
		return "us-east-1", nil
	}

	// Extract region from sts.<region>.amazonaws.com
	if !strings.HasPrefix(host, "sts.") || !strings.HasSuffix(host, ".amazonaws.com") {
		return "", fmt.Errorf("invalid AWS STS hostname: %s", host)
	}

	// Remove "sts." prefix and ".amazonaws.com" suffix
	region := strings.TrimPrefix(host, "sts.")
	region = strings.TrimSuffix(region, ".amazonaws.com")
	
	if region == "" {
		return "", fmt.Errorf("could not extract region from STS hostname: %s", host)
	}

	return region, nil
}

// validateWithAWS validates the token by making the actual AWS STS GetCallerIdentity call
func (v *Validator) validateWithAWS(ctx context.Context, tokenData *AWSTokenData, region string) (*AWSValidationResult, error) {
	// Create region-specific AWS config and STS client
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("failed to load AWS config for region %s: %w", region, err)
	}

	stsClient := sts.NewFromConfig(cfg)

	// For now, we use a simpler approach by calling GetCallerIdentity directly
	// with the STS client configured for the token's region.
	// TODO: In the future, we could replicate the exact signed request from tokenData
	// to validate that the client actually has the credentials they claim to have.
	output, err := stsClient.GetCallerIdentity(ctx, &sts.GetCallerIdentityInput{})
	if err != nil {
		return nil, fmt.Errorf("failed to call AWS STS GetCallerIdentity: %w", err)
	}

	if output.Arn == nil {
		return nil, fmt.Errorf("AWS STS response missing ARN")
	}

	result := &AWSValidationResult{
		ARN:    aws.ToString(output.Arn),
		Region: region,
	}

	if output.Account != nil {
		result.AccountID = aws.ToString(output.Account)
	}

	if output.UserId != nil {
		result.UserID = aws.ToString(output.UserId)
	}

	return result, nil
}