package aws

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"go.uber.org/zap"
)

// Validator validates AWS federated identity tokens by making actual AWS STS calls
type Validator struct {
	logger    *zap.Logger
	audiences []string
}

// AWSTokenData represents the structure of AWS token data as generated by clients
type AWSTokenData struct {
	URL     string    `json:"url"`
	Method  string    `json:"method"`
	Headers []Header  `json:"headers"`
}

// Header represents an HTTP header key-value pair
type Header struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// AWSValidationResult contains the result of AWS token validation
type AWSValidationResult struct {
	ARN string
}

// STSGetCallerIdentityResponse represents the XML response from AWS STS GetCallerIdentity
type STSGetCallerIdentityResponse struct {
	XMLName xml.Name                      `xml:"GetCallerIdentityResponse"`
	Result  STSGetCallerIdentityResult    `xml:"GetCallerIdentityResult"`
}

// STSGetCallerIdentityResult contains the result data from GetCallerIdentity
type STSGetCallerIdentityResult struct {
	ARN     string `xml:"Arn"`
	UserID  string `xml:"UserId"`
	Account string `xml:"Account"`
}

// NewValidator creates a new AWS token validator
func NewValidator(logger *zap.Logger, audiences []string) (*Validator, error) {
	return &Validator{
		logger:    logger,
		audiences: audiences,
	}, nil
}

// Validate validates an AWS federated identity token by parsing it and making an STS call
func (v *Validator) Validate(ctx context.Context, tokenData string) (map[string]string, error) {
	v.logger.Debug("validating AWS token")

	// URL decode the token
	decodedToken, err := url.QueryUnescape(tokenData)
	if err != nil {
		return nil, fmt.Errorf("failed to URL decode token: %w", err)
	}

	// Parse the JSON token
	var awsTokenData AWSTokenData
	if err := json.Unmarshal([]byte(decodedToken), &awsTokenData); err != nil {
		return nil, fmt.Errorf("failed to parse AWS token JSON: %w", err)
	}

	// Validate the audience (required)
	if err := v.validateAudience(&awsTokenData); err != nil {
		return nil, fmt.Errorf("audience validation failed: %w", err)
	}

	// Validate the token by making the actual AWS STS call
	result, err := v.validateWithAWS(ctx, &awsTokenData)
	if err != nil {
		return nil, fmt.Errorf("AWS STS validation failed: %w", err)
	}

	// Convert result to metadata map
	metadata := map[string]string{
		"io.flipt.auth.aws.arn": result.ARN,
	}

	v.logger.Debug("AWS token validation successful", 
		zap.String("arn", result.ARN))

	return metadata, nil
}

// validateAudience checks if the token contains the expected audience
func (v *Validator) validateAudience(tokenData *AWSTokenData) error {
	var tokenAudience string
	for _, header := range tokenData.Headers {
		if header.Key == "x-goog-cloud-target-resource" {
			tokenAudience = header.Value
			break
		}
	}

	if tokenAudience == "" {
		return fmt.Errorf("token does not contain required x-goog-cloud-target-resource header")
	}

	// Check if the token audience matches any of the configured audiences
	for _, audience := range v.audiences {
		if tokenAudience == audience {
			return nil
		}
	}
	
	return fmt.Errorf("token audience mismatch: token contains %q, but expected one of %v", 
		tokenAudience, v.audiences)
}


// validateWithAWS validates the token by making the exact signed AWS STS request
func (v *Validator) validateWithAWS(ctx context.Context, tokenData *AWSTokenData) (*AWSValidationResult, error) {
	// Validate the STS URL format
	if err := v.validateSTSURL(tokenData.URL); err != nil {
		return nil, fmt.Errorf("invalid STS URL: %w", err)
	}

	// Create HTTP request using the client's signed request data
	req, err := http.NewRequestWithContext(ctx, tokenData.Method, tokenData.URL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create HTTP request: %w", err)
	}

	// Add all headers from the signed token
	for _, header := range tokenData.Headers {
		req.Header.Set(header.Key, header.Value)
	}

	// Make the HTTP request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("failed to make AWS STS request: %w", err)
	}
	defer resp.Body.Close()

	// Check for HTTP errors
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("AWS STS request failed with status %d: %s", resp.StatusCode, string(body))
	}

	// Read and parse the XML response
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read AWS STS response: %w", err)
	}

	var stsResponse STSGetCallerIdentityResponse
	if err := xml.Unmarshal(respBody, &stsResponse); err != nil {
		return nil, fmt.Errorf("failed to parse AWS STS XML response: %w", err)
	}

	// Validate that we have an ARN
	if stsResponse.Result.ARN == "" {
		return nil, fmt.Errorf("AWS STS response missing ARN")
	}

	result := &AWSValidationResult{
		ARN: stsResponse.Result.ARN,
	}

	return result, nil
}

// validateSTSURL validates that the URL is a valid AWS STS endpoint
func (v *Validator) validateSTSURL(urlStr string) error {
	parsedURL, err := url.Parse(urlStr)
	if err != nil {
		return fmt.Errorf("invalid URL: %w", err)
	}

	// Must be HTTPS
	if parsedURL.Scheme != "https" {
		return fmt.Errorf("STS URL must use HTTPS, got: %s", parsedURL.Scheme)
	}

	host := parsedURL.Host
	
	// Check for global endpoint
	if host == "sts.amazonaws.com" {
		return nil
	}

	// Check for regional endpoint: sts.{region}.amazonaws.com
	if !strings.HasPrefix(host, "sts.") || !strings.HasSuffix(host, ".amazonaws.com") {
		return fmt.Errorf("invalid AWS STS hostname: %s", host)
	}

	// Extract region from sts.{region}.amazonaws.com
	region := strings.TrimPrefix(host, "sts.")
	region = strings.TrimSuffix(region, ".amazonaws.com")
	
	// Validate region format (no dots allowed for security)
	if region == "" || strings.Contains(region, ".") {
		return fmt.Errorf("invalid AWS region in hostname: %s", region)
	}

	return nil
}